/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jksjhgliztuyfpvenunn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprc2poZ2xpenR1eWZwdmVudW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1NjgwNzQsImV4cCI6MjA4OTE0NDA3NH0.4iN3WesAXJ-CD0gzFCX4sa-HOx8Q9x5jFQo0GRv7ThE"